diccionario = {
    "achik": "Luz",
    "alli": "Bueno",
    "ayllu": "Familia",
    "chaki": "Pie",
    "chaska": "Estrella",
    "churay": "Poner",
    "inti": "Sol",
    "killa": ["Luna", "Perezoso"],
    "kawsay": ["Vida", "Vivir"],
    "maki": "Mano",
    "mama": "Madre",
    "mashi": "Amigo",
    "mikuy": "Comer",
    "ñawi": "Ojo",
    "pacha": ["Tierra", "Tiempo"],
    "pukllay": "Jugar",
    "rimay": "Hablar",
    "runa": "Persona",
    "sacha": "Bosque",
    "sami": "Felicidad",
    "shimi": "Boca",
    "sisa": "Flor",
    "taita": "Padre",
    "tukuy": ["Todo", "Completo"],
    "tuta": "Noche",
    "ushai": "Fuerza",
    "wasi": ["Casa", "Hogar"],
    "yaku": "Agua",
    "yana": "Negro",
    "yura": ["Planta", "Árbol"],
    "wawa": "Niño",
    "yachay": ["Saber", "Conocimiento"],
    "yuyay": "Pensar",
    "kuyay": "Amar",
    "kuychi": "Arcoíris",
    "muyu": "Semilla",
    "nina": "Fuego",
    "puka": "Rojo",
    "rikuy": "Ver",
    "sumaq": "Hermoso",
    "taki": "Cantar",
    "tiyana": "Sentarse",
    "zarapana": "Maíz",
    "mama llacta":["nacion", "pais"],
    "chiri":"frio"
}
